### PR TITLE
Template: debug topic.thtml profile layout

### PR DESCRIPTION
**Pull request by ivywe**
Hi,

I found layout error in topic layout.
I changed topic.thtml and include/gf_showtopic.php.

Please check these  two files.

Thanks.
## 

Ivy

### CODE REVIEW

**Comment by eSilverStrike** [comment]
Hi Ivy, Thanks for the fix. I didn't know about the figcaption tag.

I will have to modify your change a bit when I get a chance. With your change you have included HTML into the code with:
```
<figcaption class="uk-thumbnail-caption">
```
We are trying to keep all html in the template files to allow for easier theme development since not all themes load uikit which would mean the  uk-thumbnail-caption class wouldn't work (with the modern curve theme for example).

**Comment by ivywe** [comment]
Hi Tom,

Okay, I see.
Please change only templates/denim/topic.thtml.

Thanks.

**Comment by eSilverStrike** [comment]
Hi Ivy,

Thanks for the pull request. I added in the figure tag along with a few other changes. I had to do it a different way to ensure it all worked with different form theme templates. I also made forum topics with users without photos look better.

See the changeset 79a64b4e50b40d50d1fda7f97c493ce8b99fefa1 for the details.

**Comment by ivywe** [comment]
thanks!

**Pull request closed without merging**
